server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
  plugins: [ ]
